# Generated by Django 4.1.3 on 2023-01-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=255)),
                ('nom_var', models.CharField(max_length=255)),
                ('sentido', models.CharField(max_length=255)),
            ],
        ),
    ]
