# Generated by Django 4.1.3 on 2023-01-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priorapp', '0002_orden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orden',
            new_name='Ordendj',
        ),
        migrations.RenameField(
            model_name='ordendj',
            old_name='orden',
            new_name='ordenv',
        ),
    ]
